version: '3.9'

services:
    u:
        build:
            context: ./
            target: development
        env_file:
            - .env
        links:
            - postgres
            - redis
        volumes:
            - ./:/opt/app
        ports:
            - 3000:3000
    postgres:
        image: postgres:latest
        container_name: postgres
        hostname: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: u
            POSTGRES_HOST_AUTH_METHOD: trust
        volumes:
            - postgres-data:/var/lib/postgresql/data
        restart: unless-stopped
    redis:
        image: redis:alpine
        container_name: redis
        hostname: redis
        ports:
            - 6379:6379
        restart: unless-stopped

volumes:
    postgres-data:
